---
projects:
    Public:
        tff:
            - "front"
        own:
            - "email"
db:
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "root"
    dbname: "tff"
listen: "8887"

